# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_times_visited'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(default='No description', max_length=120),
        ),
    ]
