# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 16:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='publish',
            new_name='publishDate',
        ),
    ]
